var kota = ["TEGALREJO","J E T I S",
"GONDOKUSUMAN","DANUREJAN","GEDONGTENGEN",
"NGAMPILAN","WIROBRAJAN","MANTRIJERON",
"KRATON","GONDOMANAN","PAKUALAMAN",
"MERGANGSAN","UMBULHARJO","KOTAGEDE"]

module.exports = kota