var derajat = ["TIDAK/BLM SEKOLAH",
"BELUM TAMAT SD/SEDERAJAT",
"TAMAT SD/SEDERAJAT",
"SLTP/SEDERAJAT",
"SLTA/SEDERAJAT",
"DIPLOMA I/II",
"AKADEMI/DIPLOMA III/SARJANA MUDA" ,
"DIPLOMA IV/STRATA I",
"STRATA-II",
"STRATA-III"  ]
module.exports =derajat